import './globals.scss'
import { Roboto } from 'next/font/google'
import {Metadata} from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const roboto = Roboto({ weight: '300', subsets: ['latin', 'cyrillic'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={roboto.className}>
        <Header/>
        <main className='container'>
            {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
